import streamlit as st
from app.api.semantic_scholar import fetch_semantic_scholar_papers
from app.api.pubmed import fetch_pubmed_papers
from app.api.google_scholar import fetch_google_scholar_papers
from app.api.arxiv import fetch_arxiv_papers
from app.utils.generate_response import generate_response

# App title and description
st.title("Sabi Boy 🤓")
st.write("Settle arguments with research-based or scientific answers. Just type your argument below!")
st.write("*Note: Answers are generated by AI and include real references from Semantic Scholar, PubMed, Google Scholar, and arXiv. Verify claims independently.*")

# User input
user_input = st.text_input("Enter your argument (e.g., 'boys live longer than girls'):")

# Generate and display response
if user_input:
    with st.spinner("Sabi Boy is thinking..."):
        # Step 1: Generate AI response
        response = generate_response(user_input)
        st.success("Sabi Boy says:")
        st.write(response)

        # Step 2: Fetch real research papers from Semantic Scholar
        st.write("### Related Research Papers from Semantic Scholar:")
        semantic_papers = fetch_semantic_scholar_papers(user_input)
        if semantic_papers:
            for paper in semantic_papers:
                title = paper.get("title", "No title available")
                authors = ", ".join([author["name"] for author in paper.get("authors", [])])
                paper_url = paper.get("url", "#")
                st.write(f"- **{title}** by {authors} ([Link]({paper_url}))")
        else:
            st.write("No relevant research papers found on Semantic Scholar.")

        # Step 3: Fetch real research papers from PubMed
        st.write("### Related Research Papers from PubMed:")
        pubmed_papers = fetch_pubmed_papers(user_input)
        if pubmed_papers:
            for paper in pubmed_papers:
                paper_id = paper.get("id")
                paper_details = paper.get("details", "No details available")
                st.write(f"- **PubMed ID: {paper_id}**")
                st.write(f"  {paper_details}")
        else:
            st.write("No relevant research papers found on PubMed.")

        # Step 4: Fetch real research papers from Google Scholar
        st.write("### Related Research Papers from Google Scholar:")
        google_scholar_papers = fetch_google_scholar_papers(user_input)
        if google_scholar_papers:
            for paper in google_scholar_papers:
                title = paper.get("title", "No title available")
                link = paper.get("link", "#")
                st.write(f"- **{title}** ([Link]({link}))")
        else:
            st.write("No relevant research papers found on Google Scholar.")

        # Step 5: Fetch real research papers from arXiv
        st.write("### Related Research Papers from arXiv:")
        arxiv_papers = fetch_arxiv_papers(user_input)
        if arxiv_papers:
            for paper in arxiv_papers:
                title = paper.get("title", "No title available")
                authors = paper.get("authors", "No authors available")
                link = paper.get("link", "#")
                st.write(f"- **{title}** by {authors} ([Link]({link}))")
        else:
            st.write("No relevant research papers found on arXiv.")